name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: actions/checkout@v3
    - name: make application.yml
      run: |
        # create application.yml
        cd ./src/main/resources
        
        # application.yml 파일 생성
        touch ./application.yml
      
        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.WAS1_APPLICATION }}" >> ./application.yml

      shell: bash

    - name: Build with Gradle
      run: |
        ./gradlew build

    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.WAS1_DOCKER_USERNAME }} -p ${{ secrets.WAS1_DOCKER_PASSWORD }}
        docker build -t ${{ secrets.WAS1_DOCKER_REPO }}/cokiri .
        docker push ${{ secrets.WAS1_DOCKER_REPO }}/cokiri 

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.WAS1_HOST }}
        username: ubuntu
        key: ${{ secrets.WAS1_PEM_KEY }}
        port: 22
        script: |
          sudo docker kill windmeal_delivery
          sudo docker container prune -f
          sudo docker pull ${{ secrets.WAS1_DOCKER_REPO }}/windmeal 
          sudo docker run -d -p 8080:8080 --name windmeal_delivery ${{ secrets.WAS1_DOCKER_REPO }}/windmeal 
